version: "3.8"
services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
    volumes:
      - ..:/workspace
    network_mode: service:db
    command: sleep infinity
  
  db:
    image: postgres:16
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: .env

volumes:
  postgres-data:

